// widgets
export const LOAD_BY_CODE = "LOAD_BY_CODE";

//city
export const GET_CITY_DETAIL = "GET_CITY_DETAIL";
export const GET_POPULAR_PAKAGES = "GET_POPULAR_PAKAGES";
export const GET_POPULAR_ATTRACTION = "GET_POPULAR_ATTRACTION";
export const GET_POPULAR_CITY_ESCAPE = "GET_POPULAR_CITY_ESCAPE";
export const GET_ELEMENT_CITY = "GET_ELEMENT_CITY";
export const GET_POPULAR_ACTIVITI = "GET_POPULAR_ACTIVITI";
export const SEARCH_CITY_ACTIVITI = "SEARCH_CITY_ACTIVITI";
export const GET_DETAIL_TICKET = "GET_DETAIL_TICKET"

//country
export const GET_ALL_DES_AU = "GET_ALL_DES_AU";


//destination
export const GET_DESTINATION_DETAIL = "GET_DESTINATION_DETAIL";
export const GET_ABOUT_DESTINATION = "GET_ABOUT_DESTINATION";


//auth
export const GET_USER_BY_TOKEN = "GET_USER_BY_TOKEN";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";

// user
export const GET_MY_WISH_LIST = "GET_MY_WISH_LIST";
export const GET_MY_BOOKING = "GET_MY_BOOKING";
export const REMOVE_MY_WISH_LIST = "REMOVE_MY_WISH_LIST";
export const GET_ALL_COUNTRY = "GET_ALL_COUNTRY";
export const UPDATE_USER_INFORMATION = "UPDATE_USER_INFORMATION";
export const GET_MY_REVIEW = "GET_MY_REVIEW";
export const CREATE_REVIEW_MY_BOOKING = " CREATE_REVIEW_MY_BOOKING";
export const UPDATE_AVATAR = "UPDATE_AVATAR"

//tour
export const GET_FILTER = "GET_FILTER";
export const GET_TOUR_BY_DESTID = "GET_TOUR_BY_DESTID";
export const GET_TOUR_DETAIL = "GET_TOUR_DETAIL";
export const LIKE_TOUR = "LIKE_TOUR";
export const LIKE_TICKET = "LIKE_TICKET";
export const UNLIKE_TOUR = "UNLIKE_TOUR";
export const UNLIKE_TICKET = "UNLIKE_TICKET";
export const SET_DEST_NAME = "SET_DEST_NAME";
export const GET_CITY_ESCAPE_BY_DESTID = "GET_CITY_ESCAPE_BY_DESTID";
export const GET_TICKET_BY_DESTID = "GET_TICKET_BY_DESTID";

// all destination
export const ALL_DESTINATION = "ALL_DESTINATION";

//search
export const GET_AUTOCOMPLETE = "GET_AUTOCOMPLETE";

// coupon
export const GET_LiST_COUPON = "GET_LiST_COUPON";
export const REDEEM_COUPON = "REDEEM_COUPON";

// flight
export const SEARCH_FLIGHT = "SEARCH_FLIGHT";
export const SET_SELECTED_FLIGHTS = 'SET_SELECTED_FLIGHTS';
export const BOOK_FLIGHT = 'BOOK_FLIGHT';

// order 
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const UPDATE_ORDER_DETAIL = "UPDATE_ORDER_DETAIL";

//coupon

export const GET_LIST_COUPON = "GET_LIST_COUPON"

//booking
export const BOOKING = "BOOKING";
export const BOOKING_TICKET = "BOOKING_TICKET"


// Chat App Actions
export const CHAT_WITH_SELECTED_USER = 'CHAT_WITH_SELECTED_USER';
export const SEND_MESSAGE_TO_USER = 'SEND_MESSAGE_TO_USER';
export const GET_ALL_CONVERSATION_CHAT = 'GET_ALL_CONVERSATION_CHAT';
export const GET_USER_CONVERSATION_CHAT = 'GET_USER_CONVERSATION_CHAT';
export const GET_ALL_MESSAGES_CHAT = 'GET_ALL_MESSAGES_CHAT';
export const REPLY_CONVERSATION_CHAT = 'REPLY_CONVERSATION_CHAT';
export const SET_READ_CONVERSATION_CHAT = "SET_READ_CONVERSATION_CHAT";
export const GET_NEW_MESSAGE_CONVERSATION_CHAT = "GET_NEW_MESSAGE_CONVERSATION_CHAT";
export const SET_NEW_MESSAGE_INBOX = "SET_NEW_MESSAGE_INBOX";
export const GET_CVS_DETAIL = "GET_CVS_DETAIL";
//config
export const GET_CONFIG = "GET_CONFIG";

// payment
export const VERIFY_PAYMENT_TOKEN = 'VERIFY_PAYMENT_TOKEN';
